name: Deploy to Vercel

on:
  push:
    branches:
      - main # 只有在推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用 Ubuntu 环境
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # 获取代码

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # 设置 Node.js 版本（可以根据项目需求调整）

      - name: Install dependencies
        run: npm install # 安装项目依赖

      - name: Build the project
        run: npm run build # 如果需要构建步骤，可以在这里加入

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: OH06f3VVr6E268BBzAwWPSVX # 使用 GitHub Secrets 中的 Vercel Token
          VERCEL_ORG_ID: mAQ1ol7qTICbEGoOpTnsdZfe # 你的 Vercel 组织 ID
          VERCEL_PROJECT_ID: prj_bC6SUXF0sfVZFtsfnu0qXB8HOo2Y # 你的 Vercel 项目 ID
        run: |
          curl -fsSL https://vercel.com/download -o vercel-linux.zip  # 下载 Vercel CLI
          unzip vercel-linux.zip -d vercel  # 解压
          ./vercel/bin/vercel login $VERCEL_TOKEN  # 登录 Vercel（通过 token）
          ./vercel/bin/vercel --token $VERCEL_TOKEN --org $VERCEL_ORG_ID --project $VERCEL_PROJECT_ID --prod  # 部署到生产环境
